# Generated by Django 5.0.7 on 2024-08-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duyuru',
            name='slug',
            field=models.SlugField(default=True, max_length=200, unique=True),
        ),
    ]
