# Generated by Django 5.0.7 on 2024-12-03 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dergi',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='dergianahtar',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='dergikaynak',
            name='ordering',
        ),
    ]
