# Generated by Django 5.0.7 on 2025-01-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/album/'),
        ),
        migrations.AlterField(
            model_name='duyuruimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/duyuru/'),
        ),
        migrations.AlterField(
            model_name='konferansimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/konferans/'),
        ),
        migrations.AlterField(
            model_name='metodolojiimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/metodoloji/'),
        ),
        migrations.AlterField(
            model_name='portre',
            name='oz_gecmis_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/portre/'),
        ),
        migrations.AlterField(
            model_name='savaimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/sava/'),
        ),
    ]
