# Generated by Django 5.0.7 on 2024-12-11 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_konu_makaleanahtar_baslik_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='makaleanahtar',
            options={'ordering': ['created']},
        ),
    ]
