# Generated by Django 5.0.7 on 2024-12-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_dergi_ordering_remove_dergianahtar_ordering_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dergi',
            name='sayi',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='dergi',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
