# Generated by Django 5.0.7 on 2024-12-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_dergimakale_pdf'),
    ]


