# Generated by Django 5.0.7 on 2024-12-11 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_makaleanahtar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='makalekaynak',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='makaleyazar',
            options={'ordering': ['created']},
        ),
    ]
