# Generated by Django 5.0.7 on 2024-12-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_album_slug_alter_duyuru_slug_alter_makale_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sayi',
            name='sayi',
            field=models.IntegerField(default=0, max_length=100, unique=True),
        ),
    ]
