# Generated by Django 5.0.7 on 2024-08-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_duyuru_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyuru',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
