# Generated by Django 5.0.7 on 2024-12-13 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_portre_image_portre_text_alter_portre_roportaj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portre',
            old_name='text',
            new_name='oz_gecmis',
        ),
        migrations.RenameField(
            model_name='portre',
            old_name='image',
            new_name='oz_gecmis_img',
        ),
    ]
