# Generated by Django 5.0.7 on 2024-12-13 05:21

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_text_portre_oz_gecmis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portre',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
