# Generated by Django 5.0.7 on 2024-08-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20240803_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duyuru',
            name='slug',
        ),
    ]
