# Generated by Django 5.0.7 on 2024-12-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_konferans_metodoloji_sava_rename_image_albumimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='tur',
            field=models.CharField(default='tür', max_length=100),
        ),
    ]
