# Generated by Django 5.0.7 on 2025-01-19 21:36

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_makale_tur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='pdf',
            field=models.FileField(blank=True, help_text='Only PDF files are allowed', null=True, upload_to='pdfs/', validators=[base.models.validate_pdf]),
        ),
    ]
