# Generated by Django 5.0.7 on 2024-08-11 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_name_image_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='album',
            new_name='name',
        ),
    ]
