# Generated by Django 5.0.7 on 2024-08-11 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_album_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duyuru',
            name='block_type',
        ),
        migrations.RemoveField(
            model_name='duyuru',
            name='image',
        ),
        migrations.RemoveField(
            model_name='duyuru',
            name='order',
        ),
    ]
