# Generated by Django 5.0.7 on 2024-09-18 23:05

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_duyuru_block_type_remove_duyuru_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
