# Generated by Django 5.0.7 on 2024-09-23 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_duyuruimage_duyurutext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duyuruimage',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='duyurutext',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='duyuru',
            name='text',
        ),
    ]
