# Generated by Django 5.0.7 on 2024-09-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_duyuruimage_options_alter_duyurutext_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duyuruimage',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='duyurutext',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
