# Generated by Django 5.0.7 on 2024-11-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_dergi_dergikeyword_dergisource_dergitext'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DergiText',
            new_name='DergiMakale',
        ),
    ]
