# Generated by Django 5.0.7 on 2024-11-27 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_rename_dergitext_dergimakale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dergimakale',
            name='text',
        ),
        migrations.CreateModel(
            name='DergiMakaleText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.dergimakale')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
