# Generated by Django 5.0.7 on 2024-11-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_dergimakale_text_dergimakaletext'),
    ]

    operations = [
        migrations.AddField(
            model_name='dergimakale',
            name='topic',
            field=models.CharField(default='makale', max_length=100),
        ),
    ]
