# Generated by Django 5.0.7 on 2024-11-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_dergimakale_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dergikeyword',
            name='keyword',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dergisource',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
