# Generated by Django 5.0.7 on 2024-11-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_dergikeyword_keyword_alter_dergisource_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dergi',
            name='author',
        ),
        migrations.AddField(
            model_name='dergimakale',
            name='author',
            field=models.CharField(default='yazar', max_length=100),
        ),
    ]
