# Generated by Django 5.0.7 on 2024-11-27 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_dergi_author_dergimakale_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dergimakaletext',
            old_name='title',
            new_name='topic',
        ),
    ]
